---
- hosts: all
  vars:
      username: '{{ cf_username }}'
      fullname: '{{ cf_fullname }}'
      password: '{{ cf_password }}'
      sudoers: '{{ cf_sudoers }}'

  tasks:
  - name: create the user
    user:
      name: '{{ username }}'
      shell: /bin/bash
      comment: '{{ fullname }}'
      password: '{{ password }}'
      update_password: always
      createhome: yes
  - name: add user to sudoers.d directory
    template:
        src: sudoers.j2
        dest: /etc/sudoers.d/'{{ username }}'.conf
    when: sudoers == true
