---
- hosts: all
  vars:
      dbname: '{{ cf_dbname }}'
      dbusername: '{{ cf_dbusername }}'
      dbuserpw: '{{ cf_dbuserpw }}'

# This stuff below here for the pass is temp.
      passhash: "{{ inventory_hostname|hash('md5')}}"
      rootpw: "{% print passhash[-10:] %}"

  tasks:
  - name: install mariadb and components
    yum:
      state: latest
      name: '{{ item }}'
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python
  - name: enable and start mariadb
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: update root for localhost account on instance
    mysql_user:
      name: root
      password: '{{ rootpw }}'
      host: localhost
  - name: Copy my.cnf to system
    template:
      src: my.j2
      dest: /root/.my.cnf
      owner: root
      mode: 0600
  - name: update rest of the root accounts on instance
    mysql_user:
      name: root
      password: '{{ rootpw }}'
      host: '{{ item }}'
    with_items:
      - 127.0.0.1
      - ::1
      - '{{ ansible_hostname }}'
  - name: remove anonymous user
    mysql_user:
      name: ''
      host: '{{ item }}'
      state: absent
    with_items:
      - localhost
      - '{{ ansible_hostname }}'
  - name: remove test database
    mysql_db:
      name: test
      state: absent
  - name: create user specified database
    mysql_db:
      name: '{{ dbname }}'
      state: present
  - name: create user with correct privileges
    mysql_user:
      name: '{{ dbusername }}'
      password: '{{ dbuserpw }}'
      host: localhost
      priv: "{{ dbname }}.*:ALTER,SELECT,UPDATE,CREATE,DELETE,DROP"
      state: present
