---
- hosts: all 
  tasks:
  - name: Create a file in /tmp
    file:
      path: /tmp/file12345
      owner: root 
      group: ansible
      mode: 0660
      state: touch
    become: true
    become_user: root 
