---
- hosts: all
  vars:
      dbname: '{{ cf_dbname }}'
      dbusername: '{{ cf_dbusername }}'
      dbuserpw: '{{ cf_dbuserpw }}'
  tasks:
  - name: install mariadb and components
    yum:
      state: latest
      name: '{{ item }}'
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python
  - name: enable and start mariadb
    service:
      name: mariadb
      state: started
      enabled: yes
  - name: create user specified database
    mysql_db:
      name: '{{ dbname }}'
      state: present
  - name: create user with correct privileges
    mysql_user:
      name: '{{ dbusername }}'
      password: '{{ dbuserpw }}'
      host: localhost
      priv: "{{ dbname }}.*:ALTER,SELECT,UPDATE,CREATE,DELETE,DROP"
      state: present
